version: "3.7"

services:
  react-app:
    build:
      context: .
      dockerfile: ./DockerFile
    container_name: my-react-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
