# Use an official Node runtime as a parent image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Add the app source code
COPY . .

# Build the app
RUN npm run build

# Set the command to run the production build
CMD ["npm", "start"]